// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylquxyvlihjbtwhvtgrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlscXV4eXZsaWhqYnR3aHZ0Z3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjcwOTAsImV4cCI6MjA2MjEwMzA5MH0._am2e3V_A2O5u11I8RPcVtywy4bNq9es9_OCFv64UMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);